import {
  BedDouble,
  Car,
  CarTaxiFrontIcon,
  Check,
  ChevronDown,
  CircleCheck,
  Gem,
  HeartIcon,
  InfoIcon,
  LucideCalendarSearch,
  MapPin,
  Minus,
  PlaneIcon,
  Plus,
  StarIcon,
  User2,
  X,
  Zap,
} from 'lucide-react';

export default {
  bed: BedDouble,
  flight: PlaneIcon,
  car: Car,
  taxi: CarTaxiFrontIcon,
  star: StarIcon,
  gem: Gem,
  heart: HeartIcon,
  check: Check,
  circleCheck: CircleCheck,
  zap: Zap,
  info: InfoIcon,
  close: X,
  location: MapPin,
  calendar: LucideCalendarSearch,
  user: User2,
  dropdown: ChevronDown,
  minus: Minus,
  plus: Plus
};
